version: "3.9"

services:
  app:
    env_file: ".env.development"
    stdin_open: true
    tty: true
    build:
      context: .
    command: bash -c 'rails db:setup && bundle exec puma -C config/puma.rb'
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:14.2-alpine3.15
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  db_volume: