default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("DATABASE_POOL") { 5 } %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOSTNAME"] %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "octo_events_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "octo_events_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "octo_events") %>
